### ISSUE TITLE
File not found...

### ISSUE THREAD

**Issue by carry0987** [bcambs09/WhatsGoodToday#1]
Hello,I can't see your config.php file...

**Comment by bcambs09** [comment]
Check the readme - it was intentionally left out to protect private information.

**Comment by carry0987** [comment]
Hello,does it look like this?

![unnamed](https://user-images.githubusercontent.com/12984973/27916892-fe4966dc-629c-11e7-8adf-5699e38060c0.jpg)


​

**Comment by bcambs09** [comment]
Yep, exactly like that!

**Comment by carry0987** [comment]
I try it,but it doesn't work..
https://www.nehscsa.com/test9/
